FROM nginx:alpine
# USER root

ENV workdir /var/www/storeserver
WORKDIR ${workdir}

COPY nginx-upload-module /usr/local/nginx-upload-module
COPY masterzen-nginx-upload-progress-module-a788dea /usr/local/masterzen-nginx-upload-progress-module-a788dea
COPY storeserver ${workdir}
COPY start.sh ${workdir}/
COPY get-pip.py ${workdir}
COPY form2.html ${workdir}/
COPY storeserver/storeserver_uwsgi.ini ${workdir}
COPY storeserver/storeserver.conf /etc/nginx/conf.d/storeserver.conf
COPY nginx.conf /etc/nginx/nginx.conf

ENV TZ=Asia/Shanghai
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
    && apk update && apk add ca-certificates \
    && apk add tzdata \
    && ln -sf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    # && apk add git \
    # && apk add curl \
    && cd /usr/local \
    # && git clone https://github.com/vkholodkov/nginx-upload-module.git \
    # && curl -sO http://nginx.org/download/nginx-1.16.1.tar.gz \
    # && tar xf nginx-1.16.1.tar.gz \
    # && rm -rf nginx-1.16.1.tar.gz \
    # && curl -s0 https://codeload.github.com/masterzen/nginx-upload-progress-module/legacy.tar.gz/v0.9.0 \
    # && tar -zxvf nginx-upload-progress-module-v0.9.0.tar.gz \
    # && rm nginx-upload-progress-module-v0.9.0.tar.gz \
    && apk --update --no-cache add geoip geoip-dev pcre libxslt gd openssl-dev pcre-dev zlib-dev build-base linux-headers libxslt-dev gd-dev libstdc++ libgcc patch logrotate supervisor inotify-tools && rm -rf /var/cache/apk/* \
    && mkdir -p /var/tmp/nginx/{client,fastcgi,proxy,uwsgi} \
    && echo "daemon off;" >> /etc/nginx/ngnix.conf \
    && apk add python3 \
    && apk add vim \
    # && apk add uwsgi \
    && apk add unzip \
    && apk add sqlite \
    && apk add openrc \
    && apk add bash \
    && apk add python3-dev \
    # install pip
    && wget https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py \
    && pip install virtualenv \
    && virtualenv ${workdir}/venv --python=python3 \
    && source ${workdir}/venv/bin/activate \
    && pip install -r ${workdir}/requirements.txt \
    && mkdir -p /run/uwsgi \
    && apk add uwsgi-http  \
    && apk add uwsgi-router_http \
    && apk add python3-dev \
    # 更新源、安装openssh 并修改配置文件和生成key 并且同步时间
    && apk update && \
    apk add --no-cache openssh && \
    sed -i "s/#PermitRootLogin.*/PermitRootLogin yes/g" /etc/ssh/sshd_config && \
       ssh-keygen -t dsa -P "" -f /etc/ssh/ssh_host_dsa_key && \
    ssh-keygen -t rsa -P "" -f /etc/ssh/ssh_host_rsa_key && \
    ssh-keygen -t ecdsa -P "" -f /etc/ssh/ssh_host_ecdsa_key && \
    ssh-keygen -t ed25519 -P "" -f /etc/ssh/ssh_host_ed25519_key && \
    echo "root:0000" | chpasswd

    # 开放22端口
EXPOSE 22 80 3001
ENV PATH /usr/local/nginx/sbin:$PATH
# CMD ["${workdir}/start.sh"]